# Generated by Django 5.1 on 2024-08-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TyouboConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registed_item_name', models.CharField(max_length=50, verbose_name='item name')),
                ('item_price', models.IntegerField(verbose_name='item price')),
                ('item_type', models.CharField(choices=[('option1', '家庭用品'), ('option2', '非家庭用品')], max_length=20)),
            ],
        ),
    ]
