# Generated by Django 5.1 on 2024-08-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyoubo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyouboconfig',
            name='item_type',
            field=models.CharField(choices=[('option1', '家庭用品'), ('option2', '非家庭用品')], max_length=20, verbose_name='item_type'),
        ),
    ]
