# Generated by Django 5.1 on 2024-08-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyoubo', '0002_alter_tyouboconfig_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyouboconfig',
            name='item_price',
            field=models.IntegerField(verbose_name='item_price'),
        ),
        migrations.AlterField(
            model_name='tyouboconfig',
            name='registed_item_name',
            field=models.CharField(max_length=50, verbose_name='item_name'),
        ),
    ]
